apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-clusterip
spec:
  ports:
  - name: web-port
	  port: 8080
    targetPort: 80  # 접근 대상 된 파드들이 내부적으로 사용하는 포트
  selector:      # 서비스에서 어떤 라벨을 가지는 파드에 접근할수있는지
	  app: webserver
	 type: ClusterIP # 서비스가 어떤 타입인지

